# Generated by Django 4.2.1 on 2025-04-18 13:00

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('other_name', models.CharField(max_length=64)),
                ('isActivated', models.BooleanField(default=True)),
                ('department', models.CharField(choices=[('AI', 'Aliwen'), ('SH', 'Say Hueque')], max_length=64)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('isActivated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('isActivated', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_clients', to='intranet.client')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='holidays date')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('tourplanId', models.CharField(max_length=64, null=True)),
                ('status', models.CharField(choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Quote Modification', 'Quote Modification'), ('Booking Modification', 'Booking Modification'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelled', 'Cancelled'), ('Program', 'Program'), ('Other', 'Other')], max_length=64)),
                ('version', models.CharField(max_length=64, null=True)),
                ('amount', models.FloatField(null=True)),
                ('client_reference', models.CharField(max_length=64, null=True)),
                ('starting_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='starting date')),
                ('conversion_date', models.DateTimeField(null=True, verbose_name='conversion date')),
                ('travelling_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='travelling date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_clients', to='intranet.client')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_contacts', to='intranet.clientcontact')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('last_modification_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last modification date')),
                ('content', models.CharField(max_length=512)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_notes', to='intranet.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('starting_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='starting date')),
                ('last_modification_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last modification date')),
                ('closing_date', models.DateTimeField(null=True, verbose_name='closing date')),
                ('response_days', models.IntegerField()),
                ('status', models.CharField(choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Quote Modification', 'Quote Modification'), ('Booking Modification', 'Booking Modification'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelled', 'Cancelled'), ('Program', 'Program'), ('Other', 'Other')], max_length=64)),
                ('amount', models.FloatField(null=True)),
                ('isClosed', models.BooleanField(default=False)),
                ('importance', models.CharField(choices=[('1', 'BAJA - min'), ('2', 'BAJA - standard'), ('3', 'BAJA - plus'), ('4', 'MED - min'), ('5', 'MED - standard'), ('6', 'MED - pide urgente'), ('7', 'ALTA - standard'), ('8', 'ALTA - pide urgente'), ('9', 'ALTA - cliente nuevo'), ('10', 'ALTA - last minute')], max_length=64)),
                ('progress', models.CharField(choices=[('0', 'No comenzado'), ('1', 'Analizado'), ('2', 'Contactados proveedores'), ('3', 'Enviado status'), ('4', 'Falta respuesta proveedor/cliente'), ('5', 'Finalizado')], default=('0', 'No comenzado'), max_length=64)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_trips', to='intranet.trip')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_creator_users', to=settings.AUTH_USER_MODEL)),
                ('user_working', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_working_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_countries', to='intranet.country'),
        ),
    ]
