# Generated by Django 4.2 on 2025-11-01 14:03

import colorfield.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('other_name', models.CharField(max_length=64)),
                ('isActivated', models.BooleanField(default=True)),
                ('department', models.CharField(choices=[('AI', 'Aliwen'), ('SH', 'Say Hueque')], max_length=64)),
                ('isAdmin', models.BooleanField(default=False)),
                ('userType', models.CharField(choices=[('Ventas', 'Ventas'), ('Operaciones', 'Operaciones'), ('DH', 'DH'), ('Internal', 'Internal'), ('Client', 'Client')], default='Ventas', max_length=64)),
                ('color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('isActivated', models.BooleanField(default=True)),
                ('department', models.CharField(choices=[('AI', 'Aliwen'), ('SH', 'Say Hueque')], max_length=64)),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='B', max_length=64)),
                ('tp_id', models.CharField(blank=True, default='', max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('isActivated', models.BooleanField(default=True)),
                ('email', models.EmailField(default='quote@aliwenincoming.com.ar', max_length=254)),
                ('client', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='client_contacts', to='intranet.client')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CsvFileTourplanFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvFiles')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelado', 'Cancelado'), ('Programa', 'Programa'), ('Bloqueo', 'Bloqueo'), ('Otro', 'Otro')], max_length=64)),
                ('version', models.IntegerField(blank=True, default=0, null=True)),
                ('version_quote', models.CharField(default='@', max_length=64, null=True)),
                ('difficulty', models.CharField(choices=[('1', 'Muy Fácil'), ('2', 'Fácil'), ('3', 'Moderado'), ('4', 'Complejo'), ('5', 'Muy Complejo')], max_length=64)),
                ('amount', models.FloatField(null=True)),
                ('client_reference', models.CharField(default='n/a', max_length=64, null=True)),
                ('starting_date', models.DateField(default=django.utils.timezone.now, verbose_name='starting date')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('conversion_date', models.DateTimeField(null=True, verbose_name='conversion date')),
                ('travelling_date', models.DateField(default=django.utils.timezone.now, verbose_name='travelling date')),
                ('out_date', models.DateField(null=True, verbose_name='out_date')),
                ('department', models.CharField(choices=[('AI', 'Aliwen'), ('SH', 'Say Hueque')], max_length=64)),
                ('tourplanId', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('itId', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('dh_type', models.CharField(choices=[('B', 'Basic'), ('S', 'Standard'), ('F', 'Full'), ('Sin definir', 'Sin definir'), ('No', 'Sin seguimiento')], default='Sin definir', max_length=64)),
                ('trip_type', models.CharField(choices=[("FIT's", "FIT's"), ('Personal Trips', 'Personal Trips'), ('FAM Tours', 'FAM Tours'), ('Grupos', 'Grupos')], default="FIT's", max_length=64)),
                ('quantity_pax', models.IntegerField(default=2)),
                ('rent_perc', models.FloatField(blank=True, default=0, null=True)),
                ('guide', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_clients', to='intranet.client')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_contacts', to='intranet.clientcontact')),
                ('creation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creation_users', to=settings.AUTH_USER_MODEL)),
                ('dh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dh_user', to=settings.AUTH_USER_MODEL)),
                ('operations_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_operations_users', to=settings.AUTH_USER_MODEL)),
                ('responsable_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_responsable_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date_from', models.DateField(verbose_name='starting_date_from')),
                ('starting_date_to', models.DateField(verbose_name='starting_date_to')),
                ('name', models.CharField(max_length=64)),
                ('client_reference', models.CharField(max_length=64)),
                ('tourplanId', models.CharField(max_length=64)),
                ('status', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelado', 'Cancelado'), ('Programa', 'Programa'), ('Bloqueo', 'Bloqueo'), ('Otro', 'Otro')], max_length=500, null=True)),
                ('difficulty', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Muy Fácil'), ('2', 'Fácil'), ('3', 'Moderado'), ('4', 'Complejo'), ('5', 'Muy Complejo')], max_length=500, null=True)),
                ('operations_user', models.ManyToManyField(blank=True, related_name='operations_users', to=settings.AUTH_USER_MODEL)),
                ('responsable_user', models.ManyToManyField(blank=True, related_name='responsable_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('last_modification_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='last modification date')),
                ('content', models.CharField(max_length=512)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_notes', to='intranet.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='holidays from')),
                ('date_to', models.DateField(verbose_name='holidays to')),
                ('type_holidays', models.CharField(choices=[('Feriado', 'Se trabaja equipo reducido'), ('Fin de semana', 'No se trabaja'), ('Día no laborable', 'Se trabaja medio día')], max_length=64)),
                ('workable', models.BooleanField(default=False)),
                ('working_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_quote', models.CharField(default='A', max_length=64)),
                ('version', models.IntegerField(blank=True, default=0, null=True)),
                ('starting_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='starting date')),
                ('last_modification_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last modification date')),
                ('closing_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='closing date')),
                ('status', models.CharField(choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelado', 'Cancelado'), ('Programa', 'Programa'), ('Bloqueo', 'Bloqueo'), ('Otro', 'Otro')], max_length=64)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('isClosed', models.BooleanField(default=False)),
                ('importance', models.CharField(choices=[('1 - BAJA - min', 'BAJA - min'), ('2 - BAJA - standard', 'BAJA - standard'), ('3 - BAJA - plus', 'BAJA - plus'), ('4 - MED - min', 'MED - min'), ('5 - MED - standard', 'MED - standard'), ('6 - MED - pide urgente', 'MED - pide urgente'), ('7 - ALTA - standard', 'ALTA - standard'), ('8 - ALTA - pide urgente', 'ALTA - pide urgente'), ('9 - ALTA - cliente nuevo', 'ALTA - cliente nuevo'), ('10 - ALTA - last minute', 'ALTA - last minute')], max_length=64)),
                ('progress', models.CharField(choices=[('0 - No comenzado', 'No comenzado'), ('1 - Analizado', 'Analizado'), ('2 - Contactados proveedores', 'Contactados proveedores'), ('3 - Enviado Status', 'Enviado status'), ('4 - Falta respuesta proveedor/cliente', 'Falta respuesta proveedor/cliente'), ('5 - Finalizado', 'Finalizado')], max_length=64)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('tourplanId', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('timingStatus', models.CharField(choices=[('light', 'En tiempo'), ('warning', 'Al límite'), ('info', 'Vencido'), ('danger', 'Muy vencido')], default='light', max_length=64)),
                ('exception', models.BooleanField(default=False)),
                ('creation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creation_users_entry', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_trips', to='intranet.trip')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_creator_users', to=settings.AUTH_USER_MODEL)),
                ('user_working', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_working_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_countries', to='intranet.country'),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='absence from')),
                ('date_to', models.DateField(verbose_name='absence to')),
                ('absence_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
