# Generated by Django 4.2 on 2025-11-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='response_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
