# Generated by Django 4.2.1 on 2025-11-10 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_entry_response_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsByWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('worked_days', models.IntegerField()),
                ('quotes_a_count', models.IntegerField(default=0)),
                ('quotes_all_count', models.IntegerField(default=0)),
                ('quotes_audley_count', models.IntegerField(default=0)),
                ('bookings_first_count', models.IntegerField(default=0)),
                ('bookings_all_count', models.IntegerField(default=0)),
                ('bookings_audley_count', models.IntegerField(default=0)),
                ('quotes_a_amount', models.IntegerField(default=0)),
                ('bookings_first_amount', models.IntegerField(default=0)),
                ('speed_all_total', models.IntegerField(default=0)),
                ('speed_all_same_day', models.IntegerField(default=0)),
                ('speed_all_one_day', models.IntegerField(default=0)),
                ('speed_all_two_days', models.IntegerField(default=0)),
                ('speed_all_three_days', models.IntegerField(default=0)),
                ('speed_all_four_days', models.IntegerField(default=0)),
                ('speed_all_five_days', models.IntegerField(default=0)),
                ('speed_all_more_days', models.IntegerField(default=0)),
                ('speed_quotes_total', models.IntegerField(default=0)),
                ('speed_quotes_same_day', models.IntegerField(default=0)),
                ('speed_quotes_one_day', models.IntegerField(default=0)),
                ('speed_quotes_two_days', models.IntegerField(default=0)),
                ('speed_quotes_three_days', models.IntegerField(default=0)),
                ('speed_quotes_four_days', models.IntegerField(default=0)),
                ('speed_quotes_five_days', models.IntegerField(default=0)),
                ('speed_quotes_more_days', models.IntegerField(default=0)),
                ('speed_bookings_total', models.IntegerField(default=0)),
                ('speed_bookings_same_day', models.IntegerField(default=0)),
                ('speed_bookings_one_day', models.IntegerField(default=0)),
                ('speed_bookings_two_days', models.IntegerField(default=0)),
                ('speed_bookings_three_days', models.IntegerField(default=0)),
                ('speed_bookings_four_days', models.IntegerField(default=0)),
                ('speed_bookings_five_days', models.IntegerField(default=0)),
                ('speed_bookings_more_days', models.IntegerField(default=0)),
                ('speed_finals_total', models.IntegerField(default=0)),
                ('speed_finals_same_day', models.IntegerField(default=0)),
                ('speed_finals_one_day', models.IntegerField(default=0)),
                ('speed_finals_two_days', models.IntegerField(default=0)),
                ('speed_finals_three_days', models.IntegerField(default=0)),
                ('speed_finals_four_days', models.IntegerField(default=0)),
                ('speed_finals_five_days', models.IntegerField(default=0)),
                ('speed_finals_more_days', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatsByClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('quotes_a_count', models.IntegerField(default=0)),
                ('quotes_all_count', models.IntegerField(default=0)),
                ('bookings_first_count', models.IntegerField(default=0)),
                ('bookings_all_count', models.IntegerField(default=0)),
                ('quotes_a_amount', models.IntegerField(default=0)),
                ('bookings_first_amount', models.IntegerField(default=0)),
                ('speed_all_average', models.IntegerField(default=0)),
                ('speed_quotes_average', models.IntegerField(default=0)),
                ('speed_bookings_average', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_clients', to='intranet.client')),
            ],
        ),
    ]
