# Generated by Django 4.2.1 on 2025-04-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_user_isadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.RemoveField(
            model_name='clientcontact',
            name='client',
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='email',
            field=models.EmailField(default='quote@aliwenincoming.com.ar', max_length=254),
        ),
    ]
