# Generated by Django 4.2.1 on 2025-04-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_alter_country_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='client',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='client_contacts', to='intranet.client'),
        ),
    ]
