# Generated by Django 4.2.1 on 2026-01-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_statsbyworker_statsbyclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('Ventas', 'Ventas'), ('Operaciones', 'Operaciones'), ('DH', 'DH'), ('Internal', 'Internal'), ('Cliente', 'Cliente')], default='Ventas', max_length=64),
        ),
    ]
