# Generated by Django 4.2.1 on 2025-04-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_clientcontact_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='department',
            field=models.CharField(choices=[('AI', 'Aliwen'), ('SH', 'Say Hueque')], default=0, max_length=64),
            preserve_default=False,
        ),
    ]
