# Generated by Django 4.2.1 on 2026-01-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_alter_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
