# Generated by Django 4.2.1 on 2026-03-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_holidays_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tariff_news',
            field=models.BooleanField(default=True),
        ),
    ]
