# Generated by Django 4.2.1 on 2025-04-24 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_trip_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='starting date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='starting_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='starting date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travelling_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='travelling date'),
        ),
    ]
