# Generated by Django 4.2.1 on 2025-04-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_trip_creation_date_alter_trip_starting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='closing date'),
        ),
    ]
