# Generated by Django 4.2.1 on 2025-05-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0007_alter_entry_amount_alter_entry_closing_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='response_days',
        ),
        migrations.AlterField(
            model_name='entry',
            name='importance',
            field=models.CharField(choices=[('1 - BAJA - min', 'BAJA - min'), ('2 - BAJA - standard', 'BAJA - standard'), ('3 - BAJA - plus', 'BAJA - plus'), ('4 - MED - min', 'MED - min'), ('5 - MED - standard', 'MED - standard'), ('6 - MED - pide urgente', 'MED - pide urgente'), ('7 - ALTA - standard', 'ALTA - standard'), ('8 - ALTA - pide urgente', 'ALTA - pide urgente'), ('9 - ALTA - cliente nuevo', 'ALTA - cliente nuevo'), ('10 - ALTA - last minute', 'ALTA - last minute')], max_length=64),
        ),
        migrations.AlterField(
            model_name='entry',
            name='progress',
            field=models.CharField(choices=[('0 - No comenzado', 'No comenzado'), ('1 - Analizado', 'Analizado'), ('2 - Contactados proveedores', 'Contactados proveedores'), ('3 - Enviado Status', 'Enviado status'), ('4 - Falta respuesta proveedor/cliente', 'Falta respuesta proveedor/cliente'), ('5 - Finalizado', 'Finalizado')], default=('0 - No comenzado', 'No comenzado'), max_length=64),
        ),
        migrations.AlterField(
            model_name='entry',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
