# Generated by Django 4.2.1 on 2026-03-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0007_user_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_tp',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
