# Generated by Django 4.2.1 on 2026-03-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0008_user_other_tp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='dh',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
