# Generated by Django 4.2.1 on 2026-03-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0009_alter_trip_dh'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='ignore_margin_warning',
            field=models.BooleanField(default=False),
        ),
    ]
