# Generated by Django 4.2.1 on 2025-05-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-starting_date']},
        ),
        migrations.AddField(
            model_name='client',
            name='department',
            field=models.CharField(choices=[('AI', 'Aliwen'), ('SH', 'Say Hueque')], default='AI', max_length=64),
            preserve_default=False,
        ),
    ]
