# Generated by Django 4.2.1 on 2026-03-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0010_add_ignore_margin_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='margin_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
