# Generated by Django 4.2.1 on 2025-05-03 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0010_alter_entry_options_client_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='working_user',
            field=models.ManyToManyField(blank=True, related_name='working_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
