# Generated by Django 4.2.1 on 2025-05-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0011_holidays_working_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='client_reference',
            field=models.CharField(default='n/a', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='version',
            field=models.CharField(default=0, max_length=64, null=True),
        ),
    ]
