# Generated by Django 4.2.1 on 2025-05-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0012_alter_trip_client_reference_alter_trip_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='version',
            field=models.IntegerField(default=0, max_length=64, null=True),
        ),
    ]
