# Generated by Django 4.2.1 on 2025-05-03 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0013_alter_trip_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='closing_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='closing date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelled', 'Cancelled'), ('Program', 'Program'), ('Bloqueo', 'Bloqueo'), ('Other', 'Other')], max_length=64),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelled', 'Cancelled'), ('Program', 'Program'), ('Bloqueo', 'Bloqueo'), ('Other', 'Other')], max_length=64),
        ),
        migrations.AlterField(
            model_name='trip',
            name='version',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
