# Generated by Django 4.2.1 on 2026-05-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0013_guide_location_fk_dh_location_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tp_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
