# Generated by Django 4.2.1 on 2025-05-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0014_alter_entry_closing_date_alter_entry_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='version',
        ),
        migrations.AddField(
            model_name='entry',
            name='version_booking',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='version_quote',
            field=models.CharField(default='1', max_length=64),
        ),
        migrations.AlterField(
            model_name='entry',
            name='progress',
            field=models.CharField(choices=[('0 - No comenzado', 'No comenzado'), ('1 - Analizado', 'Analizado'), ('2 - Contactados proveedores', 'Contactados proveedores'), ('3 - Enviado Status', 'Enviado status'), ('4 - Falta respuesta proveedor/cliente', 'Falta respuesta proveedor/cliente'), ('5 - Finalizado', 'Finalizado')], max_length=64),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelado', 'Cancelado'), ('Programa', 'Programa'), ('Bloqueo', 'Bloqueo'), ('Otro', 'Otro')], max_length=64),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelado', 'Cancelado'), ('Programa', 'Programa'), ('Bloqueo', 'Bloqueo'), ('Otro', 'Otro')], max_length=64),
        ),
        migrations.AlterField(
            model_name='trip',
            name='version',
            field=models.CharField(default='0', max_length=64, null=True),
        ),
    ]
