# Generated by Django 4.2.1 on 2025-05-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0015_remove_entry_version_entry_version_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='version_booking',
        ),
        migrations.AddField(
            model_name='entry',
            name='version',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='version_quote',
            field=models.CharField(default='A', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='version_quote',
            field=models.CharField(default='A', max_length=64),
        ),
        migrations.AlterField(
            model_name='trip',
            name='version',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
