# Generated by Django 4.2.1 on 2025-05-09 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0017_trip_dh_type_trip_itid_trip_trip_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='dh',
            field=models.CharField(choices=[('Mariana', 'Mariana'), ('Marina', 'Marina'), ('Camila Parra', 'Camila'), ('Sin definir', 'Sin definir')], default='Sin definir', max_length=64),
        ),
        migrations.AddField(
            model_name='trip',
            name='guide',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='operations_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_operations_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='out_date',
            field=models.DateField(null=True, verbose_name='out_date'),
        ),
        migrations.AddField(
            model_name='trip',
            name='quantity_pax',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='responsable_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_responsable_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
