# Generated by Django 4.2.1 on 2025-05-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0018_trip_dh_trip_guide_trip_operations_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='quantity_pax',
            field=models.IntegerField(default=2),
        ),
    ]
