# Generated by Django 4.2.1 on 2025-05-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0019_alter_trip_quantity_pax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='itId',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tourplanId',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
