# Generated by Django 4.2.1 on 2025-05-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0020_alter_trip_itid_alter_trip_tourplanid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Operations', 'Operations')], default='Sales', max_length=64),
        ),
    ]
