# Generated by Django 4.2.1 on 2026-06-16 15:06

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0040_feedback_priority'),
        ('intranet', '0022_externalcalendarentry_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='notificationpreference',
            name='unique_user_notification_type',
        ),
        migrations.AlterField(
            model_name='absence',
            name='type_absence',
            field=models.CharField(choices=[('Vacaciones', 'Vacaciones'), ('Beneficio Vacaciones', 'Beneficio Vacaciones'), ('Compensatorios', 'Compensatorios'), ('Cumpleaños', 'Cumpleaños'), ('Cumpleaños en baja', 'Cumpleaños en baja'), ('Enfermedad', 'Enfermedad'), ('Exámenes/Día de Estudio', 'Exámenes/Día de Estudio'), ('FAM/Trabajando fuera ofi', 'FAM/Trabajando fuera ofi'), ('Feriado trabajado', 'Feriado trabajado'), ('Feriado trabajado 1/2', 'Feriado trabajado 1/2'), ('Semana home', 'Semana home'), ('Sin goce de sueldo', 'Sin goce de sueldo'), ('Viernes OFF', 'Viernes OFF')], default='Vacaciones', max_length=64),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelado', 'Cancelado'), ('Queja', 'Queja'), ('Programa', 'Programa'), ('Bloqueo', 'Bloqueo'), ('Otro', 'Otro')], max_length=64),
        ),
        migrations.AlterField(
            model_name='externalcalendarentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='type_holidays',
            field=models.CharField(choices=[('Feriado', 'Se trabaja equipo reducido'), ('Fin de semana', 'No se trabaja'), ('Día no laborable', 'Se trabaja medio día o día completo')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='search',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelado', 'Cancelado'), ('Queja', 'Queja'), ('Programa', 'Programa'), ('Bloqueo', 'Bloqueo'), ('Otro', 'Otro')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelado', 'Cancelado'), ('Queja', 'Queja'), ('Programa', 'Programa'), ('Bloqueo', 'Bloqueo'), ('Otro', 'Otro')], max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('Ventas', 'Ventas'), ('Operaciones', 'Operaciones'), ('Manager', 'Manager'), ('DH', 'DH'), ('Internal', 'Internal'), ('Cliente', 'Cliente')], default='Ventas', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'notification_type')},
        ),
        migrations.AddField(
            model_name='driver',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='tariff.location'),
        ),
    ]
