# Generated by Django 4.2.1 on 2026-06-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0041_driver_model'),
        ('intranet', '0023_driver_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='tariff.supplier', verbose_name='Proveedor/Transportista'),
        ),
    ]
