# Generated by Django 4.2.1 on 2025-05-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0023_alter_trip_dh_alter_trip_guide_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('Ventas', 'Ventas'), ('Operaciones', 'Operaciones'), ('DH', 'DH'), ('Internal', 'Internal')], default='Sales', max_length=64),
        ),
    ]
