# Generated by Django 4.2.1 on 2026-06-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0024_driver_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='last_followup_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último seguimiento enviado'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('tariff_client', 'Tariff Updates – Clients'), ('tariff_team', 'Tariff Updates – Team (Internal)'), ('margin_warning', 'Margin Warnings (Sellers)'), ('margin_manager', 'Margin Report (Manager)'), ('weekly_roster', 'Weekly Roster'), ('holiday_reminder', 'Holiday Reminder'), ('quality_closure', 'Calidad – Resumen de cierre')], max_length=40),
        ),
    ]
