# Generated by Django 4.2.1 on 2025-05-10 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0024_alter_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='creation_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creation_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
