# Generated by Django 4.2.1 on 2025-05-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0025_trip_creation_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-creation_date']},
        ),
    ]
