# Generated by Django 4.2.1 on 2025-05-11 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0026_alter_trip_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
