# Generated by Django 4.2.1 on 2025-05-11 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0027_notes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='last_modification_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='last modification date'),
        ),
    ]
