# Generated by Django 4.2.1 on 2025-05-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0028_alter_notes_last_modification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='B', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('Ventas', 'Ventas'), ('Operaciones', 'Operaciones'), ('DH', 'DH'), ('Internal', 'Internal'), ('Client', 'Client')], default='Sales', max_length=64),
        ),
    ]
