# Generated by Django 4.2.1 on 2025-06-10 02:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0029_client_category_alter_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFileTourplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvFiles')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='holidays date')),
                ('absence_user', models.ManyToManyField(blank=True, related_name='absence_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
