# Generated by Django 4.2.1 on 2025-06-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0030_csvfiletourplan_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='difficulty',
            field=models.CharField(choices=[(1, 'Muy Fácil'), (2, 'Fácil'), (3, 'Moderado'), (4, 'Complejo'), (5, 'Muy Complejo')], default=3, max_length=64),
            preserve_default=False,
        ),
    ]
