# Generated by Django 4.2.1 on 2025-06-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0031_entry_note_trip_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Muy Fácil'), ('2', 'Fácil'), ('3', 'Moderado'), ('4', 'Complejo'), ('5', 'Muy Complejo')], max_length=64),
        ),
    ]
