# Generated by Django 4.2.1 on 2025-06-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0033_client_tp_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CsvFileTourplan',
            new_name='CsvFileTourplanFiles',
        ),
    ]
