# Generated by Django 4.2.1 on 2025-06-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0036_alter_csvfiletourplanfiles_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfiletourplanfiles',
            name='user',
        ),
    ]
