# Generated by Django 4.2.1 on 2025-06-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0038_trip_rentability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='rentability',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
