# Generated by Django 4.2.1 on 2025-06-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0039_alter_trip_rentability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='rentability',
        ),
        migrations.AddField(
            model_name='trip',
            name='rent_perc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
