# Generated by Django 4.2 on 2025-08-11 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0040_remove_trip_rentability_trip_rent_perc'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='creation_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creation_users_entry', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
