# Generated by Django 4.2 on 2025-08-23 16:09

from django.conf import settings
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0041_entry_creation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date_from', models.DateField(verbose_name='starting_date_from')),
                ('starting_date_to', models.DateField(verbose_name='starting_date_to')),
                ('name', models.CharField(max_length=64)),
                ('client_reference', models.CharField(max_length=64)),
                ('tourplanId', models.CharField(max_length=64)),
                ('status', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelado', 'Cancelado'), ('Programa', 'Programa'), ('Bloqueo', 'Bloqueo'), ('Otro', 'Otro')], max_length=500, null=True)),
                ('difficulty', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Muy Fácil'), ('2', 'Fácil'), ('3', 'Moderado'), ('4', 'Complejo'), ('5', 'Muy Complejo')], max_length=500, null=True)),
                ('operations_user', models.ManyToManyField(blank=True, related_name='voperations_users', to=settings.AUTH_USER_MODEL)),
                ('responsable_user', models.ManyToManyField(blank=True, related_name='responsable_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
