# Generated by Django 4.2 on 2025-08-23 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0042_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='search_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
