# Generated by Django 4.2 on 2025-08-24 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0043_search_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='operations_user',
            field=models.ManyToManyField(blank=True, related_name='operations_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
