# Generated by Django 4.2 on 2025-08-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0044_alter_search_operations_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='entry',
            name='tourplanId',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
