# Generated by Django 4.2 on 2025-09-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0045_alter_entry_options_entry_tourplanid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='date',
        ),
        migrations.RemoveField(
            model_name='holidays',
            name='date',
        ),
        migrations.AddField(
            model_name='absence',
            name='date_from',
            field=models.DateField(default=None, verbose_name='absence from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absence',
            name='date_to',
            field=models.DateField(default=None, verbose_name='absence to'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holidays',
            name='date_from',
            field=models.DateField(default=None, verbose_name='holidays from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holidays',
            name='date_to',
            field=models.DateField(default=None, verbose_name='holidays to'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holidays',
            name='type_holidays',
            field=models.CharField(choices=[('Feriado', 'Se trabaja equipo reducido'), ('Fin de semana', 'No se trabaja'), ('Día no laborable', 'Se trabaja medio día')], default=2, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holidays',
            name='workable',
            field=models.BooleanField(default=False),
        ),
    ]
