# Generated by Django 4.2 on 2025-09-08 17:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0046_remove_absence_date_remove_holidays_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
