# Generated by Django 4.2 on 2025-09-08 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0047_user_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='absence_user',
        ),
        migrations.RemoveField(
            model_name='holidays',
            name='working_user',
        ),
        migrations.AddField(
            model_name='absence',
            name='absence_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holidays',
            name='working_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
