# Generated by Django 4.2 on 2025-09-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0048_remove_absence_absence_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='exception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='timingStatus',
            field=models.CharField(choices=[('light', 'En tiempo'), ('warning', 'Al límite'), ('info', 'Vencido'), ('danger', 'Muy vencido')], default='light', max_length=64),
        ),
    ]
