# Generated by Django 4.2.1 on 2026-08-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0067_department_sh_to_dm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='department',
            field=models.CharField(choices=[('AI', 'Aliwen'), ('DM', 'Say Hueque DMC'), ('GR', 'Say Hueque Grupos')], max_length=64),
        ),
        migrations.AlterField(
            model_name='trip',
            name='department',
            field=models.CharField(choices=[('AI', 'Aliwen'), ('DM', 'Say Hueque DMC'), ('GR', 'Say Hueque Grupos')], max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('AI', 'Aliwen'), ('DM', 'Say Hueque DMC'), ('GR', 'Say Hueque Grupos')], max_length=64),
        ),
    ]
