# Generated by Django 4.2.1 on 2026-08-13 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0068_alter_department_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PublicItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('intro_text', models.TextField(blank=True, default='')),
                ('cover_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('show_prices', models.BooleanField(default=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=8)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('synced_from_tourplan_at', models.DateTimeField(blank=True, null=True)),
                ('edited_manually_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_itineraries', to=settings.AUTH_USER_MODEL)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_itinerary', to='intranet.entry')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('service_code', models.CharField(blank=True, default='', max_length=4)),
                ('supplier_code', models.CharField(blank=True, default='', max_length=6)),
                ('option_code', models.CharField(blank=True, default='', max_length=6)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=200)),
                ('option_description', models.CharField(blank=True, default='', max_length=300)),
                ('custom_title', models.CharField(blank=True, default='', max_length=200)),
                ('custom_description', models.TextField(blank=True, default='')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='intranet.itineraryday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='intranet.publicitinerary'),
        ),
    ]
