# Generated by Django 4.2.1 on 2026-08-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0069_public_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryline',
            name='location_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
