# Generated by Django 4.2.1 on 2026-08-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0070_itinerary_line_location_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryline',
            name='title_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='itineraryline',
            name='option_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
