# Generated by Django 4.2.1 on 2026-08-14 01:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0071_itinerary_line_title_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelado', 'Cancelado'), ('Queja', 'Queja'), ('Programa', 'Programa'), ('Pre-Quote', 'Pre-Quote'), ('Bloqueo', 'Bloqueo'), ('Otro', 'Otro')], max_length=64),
        ),
        migrations.AlterField(
            model_name='search',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelado', 'Cancelado'), ('Queja', 'Queja'), ('Programa', 'Programa'), ('Pre-Quote', 'Pre-Quote'), ('Bloqueo', 'Bloqueo'), ('Otro', 'Otro')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Quote', 'Quote'), ('Booking', 'Booking'), ('Final Itinerary', 'Final Itinerary'), ('Void', 'Void'), ('Cancelado', 'Cancelado'), ('Queja', 'Queja'), ('Programa', 'Programa'), ('Pre-Quote', 'Pre-Quote'), ('Bloqueo', 'Bloqueo'), ('Otro', 'Otro')], max_length=64),
        ),
    ]
