# Generated by Django 4.2.1 on 2026-08-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0072_alter_status_choices_pre_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryline',
            name='conditions_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='itineraryline',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itineraryline',
            name='room_summary',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='publicitinerary',
            name='important_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publicitinerary',
            name='prepayments_required',
            field=models.TextField(blank=True, default=''),
        ),
    ]
