# Generated by Django 4.2.1 on 2026-08-20 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0074_usertablepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='responsable_user_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_responsable_users_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
