# Generated by Django 4.2.1 on 2026-08-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0075_trip_responsable_user_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryline',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='itineraryline',
            name='nights',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicitinerary',
            name='consultant_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='publicitinerary',
            name='pax_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicitinerary',
            name='sustainability_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='publicitinerary',
            name='trip_style',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
