# Generated by Django 4.2.1 on 2026-08-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0076_itinerary_design_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicitinerary',
            name='intro_text',
            field=models.TextField(blank=True, default='Argentina is a land of contrasts that never ceases to amaze. The many natural wonders are breath-taking and marvelously unspoiled. Subtropical rainforests and spectacular waterfalls in Iguazu, the immense Perito Moreno Glacier, the sparkling lakes and rolling green hills of the Lake District, salt flats and cloud forest jungle near Salta, whales basking in the bay at Peninsula Valdes, and of course the miles of gaucho (cowboy) filled Estancia country for which Argentina is so famous. The combination of all this natural beauty, together with one of the most buzzing and cosmopolitan capitals in South America, delightful colonial towns, a luxurious wine region and a population of friendly and welcoming people you really can’t go wrong with a trip to Argentina. It truly has something for everyone.'),
        ),
    ]
