# Generated by Django 4.2.1 on 2026-08-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0077_itinerary_default_intro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryline',
            name='image_url_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='itineraryline',
            name='image_url_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
