# Generated by Django 4.2.1 on 2026-08-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0078_itinerary_line_multi_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='revision_blocked',
            field=models.BooleanField(default=False, help_text='Si está tildado, no se le asignan automáticamente itinerarios para revisar.', verbose_name='Bloqueado para revisiones'),
        ),
    ]
