# Generated by Django 4.2.1 on 2026-08-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0079_user_revision_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='revision_assigned_date',
            field=models.DateField(blank=True, help_text='Día en que se asignó revising_user (automática o manualmente); usado para balancear la carga del día.', null=True, verbose_name='Fecha de asignación de revisión'),
        ),
        migrations.AlterField(
            model_name='user',
            name='seniority',
            field=models.CharField(blank=True, choices=[('Principiante', 'Principiante'), ('Junior', 'Junior'), ('Senior', 'Senior')], default='', max_length=20),
        ),
    ]
