# Generated by Django 4.2.1 on 2026-08-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0080_entry_revision_assigned_date_alter_user_seniority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='type_absence',
            field=models.CharField(choices=[('Vacaciones', 'Vacaciones'), ('Beneficio Vacaciones', 'Beneficio Vacaciones'), ('Compensatorios', 'Compensatorios'), ('Cumpleaños', 'Cumpleaños'), ('Cumpleaños en baja', 'Cumpleaños en baja'), ('Enfermedad', 'Enfermedad'), ('Exámenes/Día de Estudio', 'Exámenes/Día de Estudio'), ('FAM/Trabajando fuera ofi', 'FAM/Trabajando fuera ofi'), ('Feriado trabajado', 'Feriado trabajado'), ('Feriado trabajado 1/2', 'Feriado trabajado 1/2'), ('Licencia con goce', 'Licencia con goce'), ('Licencia sin goce', 'Licencia sin goce'), ('Semana home', 'Semana home'), ('Sin goce de sueldo', 'Sin goce de sueldo'), ('Viernes OFF', 'Viernes OFF')], default='Vacaciones', max_length=64),
        ),
    ]
