# Generated by Django 4.2.1 on 2026-09-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0081_alter_absence_type_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='revised_date',
            field=models.DateField(blank=True, help_text='Día en que se marcó is_revised=True; usado para mostrarlo tachado en el listado del día.', null=True, verbose_name='Fecha de revisión'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('tariff_client', 'Tariff Updates – Clients'), ('tariff_team', 'Tariff Updates – Team (Internal)'), ('margin_warning', 'Margin Warnings (Sellers)'), ('margin_manager', 'Margin Report (Manager)'), ('weekly_roster', 'Weekly Roster'), ('holiday_reminder', 'Holiday Reminder'), ('quality_closure', 'Calidad – Resumen de cierre'), ('closure_reminder', 'Recordatorio de Cierre de Files (Operaciones)')], max_length=40),
        ),
    ]
