# Generated by Django 4.2.1 on 2026-09-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0082_entry_revised_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='revised_date',
            field=models.DateTimeField(blank=True, help_text='Momento en que se marcó is_revised=True; usado para mostrarlo tachado en el listado del día y para medir cuánto tardó la revisión.', null=True, verbose_name='Fecha y hora de revisión'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='revision_assigned_date',
            field=models.DateTimeField(blank=True, help_text='Momento en que se asignó revising_user (automática o manualmente); usado para balancear la carga del día y medir cuánto tardó la revisión.', null=True, verbose_name='Fecha y hora de asignación de revisión'),
        ),
    ]
