# Generated by Django 4.2.1 on 2026-09-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0083_alter_entry_revised_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryline',
            name='missing_prepayment',
            field=models.BooleanField(default=False),
        ),
    ]
