# Generated by Django 4.2.1 on 2026-09-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0084_itineraryline_missing_prepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='intranet.publicitinerary')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
