# Generated by Django 4.2.1 on 2026-09-09 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0085_itinerarypassenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='VrAssignmentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('AI', 'Aliwen'), ('DM', 'Say Hueque DMC'), ('GR', 'Say Hueque Grupos')], max_length=64)),
                ('month', models.DateField(help_text='Día 1 del mes de viaje (travelling_date).')),
                ('assigned_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('department', 'month')},
            },
        ),
    ]
