# Generated by Django 4.2.1 on 2026-09-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0086_vrassignmentround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('tariff_client', 'Tariff Updates – Clients'), ('tariff_team', 'Tariff Updates – Team (Internal)'), ('margin_warning', 'Margin Warnings (Sellers)'), ('margin_manager', 'Margin Report (Manager)'), ('weekly_roster', 'Weekly Roster'), ('holiday_reminder', 'Holiday Reminder'), ('quality_closure', 'Calidad – Resumen de cierre'), ('closure_reminder', 'Recordatorio de Cierre de Files (Operaciones)'), ('vr_missing_reminder', 'Files sin VR asignado (Manager)')], max_length=40),
        ),
    ]
