# Generated by Django 4.2.1 on 2026-09-10 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0087_alter_notificationpreference_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cavo_assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='cavo_is_revised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='cavo_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='cavo_revised_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='cavo_revising_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cavo_revising_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='cavo_chat_webhook_url',
            field=models.URLField(blank=True, default='', verbose_name='Google Chat Webhook URL (CAVO)'),
        ),
    ]
