# Generated by Django 4.2.1 on 2026-09-10 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _copy_webhooks_forward(apps, schema_editor):
    """Carry any already-configured webhook URLs over to the new centralized
    ChatWebhook model before the old per-user fields are dropped — the
    entries-correction one is live in production and must not be lost."""
    User = apps.get_model('intranet', 'User')
    ChatWebhook = apps.get_model('intranet', 'ChatWebhook')

    departments = User.objects.values_list('department', flat=True).distinct()
    for department in departments:
        if not department:
            continue
        entries_user = (
            User.objects.filter(department=department)
            .exclude(chat_webhook_url='').first()
        )
        if entries_user:
            ChatWebhook.objects.update_or_create(
                department=department, purpose='entries_correction',
                defaults={'webhook_url': entries_user.chat_webhook_url},
            )
        cavo_user = (
            User.objects.filter(department=department)
            .exclude(cavo_chat_webhook_url='').first()
        )
        if cavo_user:
            ChatWebhook.objects.update_or_create(
                department=department, purpose='cavo',
                defaults={'webhook_url': cavo_user.cavo_chat_webhook_url},
            )


def _copy_webhooks_backward(apps, schema_editor):
    pass  # old fields are gone by the time this would run; nothing to restore into


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0088_trip_cavo_assigned_date_trip_cavo_is_revised_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('AI', 'Aliwen'), ('DM', 'Say Hueque DMC'), ('GR', 'Say Hueque Grupos')], max_length=64)),
                ('purpose', models.CharField(choices=[('entries_correction', 'Correcciones de entradas'), ('cavo', 'CAVO')], max_length=40)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('department', 'purpose')},
            },
        ),
        migrations.RunPython(_copy_webhooks_forward, _copy_webhooks_backward),
        migrations.RemoveField(
            model_name='user',
            name='cavo_chat_webhook_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chat_webhook_url',
        ),
    ]
