# Generated by Django 4.2.1 on 2026-09-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0089_remove_user_cavo_chat_webhook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatwebhook',
            name='purpose',
            field=models.CharField(choices=[('entries_correction', 'Correcciones de entradas'), ('cavo', 'Corrección de CAVOs')], max_length=40),
        ),
    ]
