# Generated by Django 4.2.1 on 2026-09-15 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0090_alter_chatwebhook_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='CavoCorrectorRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('AI', 'Aliwen'), ('DM', 'Say Hueque DMC'), ('GR', 'Say Hueque Grupos')], max_length=64)),
                ('order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cavo_roster_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department', 'order'],
                'unique_together': {('department', 'user')},
            },
        ),
    ]
