# Generated by Django 4.2.1 on 2026-09-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0091_cavocorrectorroster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cavocorrectorroster',
            options={'ordering': ['department', 'seguimiento_type', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='cavocorrectorroster',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cavocorrectorroster',
            name='seguimiento_type',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('STD', 'Standard'), ('FULL', 'Full')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='cavo_seguimiento',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='cavocorrectorroster',
            unique_together={('department', 'seguimiento_type', 'user')},
        ),
    ]
