# Generated by Django 4.2.1 on 2025-05-31 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('pic1_url', models.CharField(max_length=500)),
                ('pic2_url', models.CharField(max_length=500)),
                ('pic3_url', models.CharField(max_length=500)),
                ('children_ranking', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=64)),
                ('disabled_ranking', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=64)),
                ('attractions', multiselectfield.db.fields.MultiSelectField(choices=[('CITY', 'City'), ('FALLS', 'Falls'), ('MOUNTAINS', 'Mountains'), ('COUNTRYSIDE', 'Countryside'), ('GLACIERS', 'Glaciers'), ('WILDLIFE', 'Wildlife')], max_length=500)),
                ('interests', multiselectfield.db.fields.MultiSelectField(choices=[('FOOD', 'Food'), ('MUSIC', 'Music'), ('ART', 'Art'), ('TREKKING', 'Trekking'), ('ACTIVE', 'Active Activities'), ('RELAXING', 'Relaxing'), ('LANDSCAPES', 'Landscapes'), ('NATURE', 'Nature'), ('CULTURE', 'Culture')], max_length=500)),
                ('min_nights', models.PositiveSmallIntegerField()),
                ('max_nights', models.PositiveSmallIntegerField()),
                ('margin', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('pic1_url', models.CharField(max_length=500)),
                ('pic2_url', models.CharField(max_length=500)),
                ('pic3_url', models.CharField(max_length=500)),
                ('children_ranking', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=64)),
                ('disabled_ranking', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=64)),
                ('attractions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CITY', 'City'), ('FALLS', 'Falls'), ('MOUNTAINS', 'Mountains'), ('COUNTRYSIDE', 'Countryside'), ('GLACIERS', 'Glaciers'), ('WILDLIFE', 'Wildlife')], max_length=64, null=True)),
                ('interests', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FOOD', 'Food'), ('MUSIC', 'Music'), ('ART', 'Art'), ('TREKKING', 'Trekking'), ('ACTIVE', 'Active Activities'), ('RELAXING', 'Relaxing'), ('LANDSCAPES', 'Landscapes'), ('NATURE', 'Nature'), ('CULTURE', 'Culture')], max_length=64, null=True)),
                ('isActivated', models.BooleanField(default=True)),
                ('type_service', models.CharField(choices=[('AC', 'Accommodation'), ('NA', 'Non-accommodation')], max_length=64)),
                ('recommended', models.BooleanField(default=False)),
                ('real_supplier', models.CharField(max_length=64)),
                ('shown', models.BooleanField(default=True)),
                ('fcu', models.CharField(choices=[('Group', 'Group'), ('Person', 'Person')], max_length=64)),
                ('scu', models.PositiveSmallIntegerField()),
                ('lw_date', models.DateField(default=django.utils.timezone.now, verbose_name='last_working_date')),
                ('quality', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SupplierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('pic1_url', models.CharField(max_length=500)),
                ('pic2_url', models.CharField(max_length=500)),
                ('pic3_url', models.CharField(max_length=500)),
                ('children_ranking', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=64)),
                ('disabled_ranking', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=64)),
                ('attractions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CITY', 'City'), ('FALLS', 'Falls'), ('MOUNTAINS', 'Mountains'), ('COUNTRYSIDE', 'Countryside'), ('GLACIERS', 'Glaciers'), ('WILDLIFE', 'Wildlife')], max_length=64, null=True)),
                ('interests', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FOOD', 'Food'), ('MUSIC', 'Music'), ('ART', 'Art'), ('TREKKING', 'Trekking'), ('ACTIVE', 'Active Activities'), ('RELAXING', 'Relaxing'), ('LANDSCAPES', 'Landscapes'), ('NATURE', 'Nature'), ('CULTURE', 'Culture')], max_length=64, null=True)),
                ('note', models.CharField(blank=True, default=None, max_length=500)),
                ('recommended', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('margin', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_products', to='tariff.suppliergroup')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='from_date')),
                ('date_to', models.DateField(verbose_name='to_date')),
                ('season', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Provisional', 'Provisional')], max_length=64)),
                ('cost', models.PositiveIntegerField()),
                ('margin', models.FloatField()),
                ('increase', models.FloatField(blank=True, null=True)),
                ('sell', models.PositiveIntegerField()),
                ('column_options', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_rate', to='tariff.rategroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_products', to='tariff.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_products', to='tariff.productgroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_products', to='tariff.location'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='tariff.supplier'),
        ),
        migrations.CreateModel(
            name='FixedRateCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='from_date')),
                ('date_to', models.DateField(verbose_name='to_date')),
                ('increase', models.FloatField(blank=True, null=True)),
                ('usd', models.BooleanField(default=True)),
                ('exchange', models.PositiveIntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_rate_location', to='tariff.location')),
            ],
        ),
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('usd', models.BooleanField(default=True)),
                ('exchange', models.PositiveIntegerField(default=1)),
                ('tax', models.CharField(choices=[(0, '0 - No taxes'), (10.5, '10.5 - Transport'), (21, '21 - Other')], max_length=64)),
                ('value', models.PositiveIntegerField()),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='tariff.rate')),
            ],
        ),
    ]
