# Generated by Django 4.2 on 2025-11-01 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intranet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFileTourplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvFiles')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('pic1_url', models.CharField(blank=True, max_length=500, null=True)),
                ('pic2_url', models.CharField(blank=True, max_length=500, null=True)),
                ('pic3_url', models.CharField(blank=True, max_length=500, null=True)),
                ('children_ranking', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('disabled_ranking', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('sustentability_ranking', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('attractions', multiselectfield.db.fields.MultiSelectField(choices=[('CITY', 'City'), ('FALLS', 'Falls'), ('MOUNTAINS', 'Mountains'), ('COUNTRYSIDE', 'Countryside'), ('GLACIERS', 'Glaciers'), ('WILDLIFE', 'Wildlife')], max_length=500)),
                ('interests', multiselectfield.db.fields.MultiSelectField(choices=[('FOOD', 'Food'), ('MUSIC', 'Music'), ('ART', 'Art'), ('TREKKING', 'Trekking'), ('ACTIVE', 'Active Activities'), ('RELAXING', 'Relaxing'), ('LANDSCAPES', 'Landscapes'), ('NATURE', 'Nature'), ('CULTURE', 'Culture')], max_length=500)),
                ('min_nights', models.PositiveSmallIntegerField()),
                ('max_nights', models.PositiveSmallIntegerField()),
                ('margin_svs', models.FloatField()),
                ('margin_acc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('pic1_url', models.CharField(blank=True, max_length=500, null=True)),
                ('pic2_url', models.CharField(blank=True, max_length=500, null=True)),
                ('pic3_url', models.CharField(blank=True, max_length=500, null=True)),
                ('children_ranking', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('disabled_ranking', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('sustentability_ranking', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('attractions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CITY', 'City'), ('FALLS', 'Falls'), ('MOUNTAINS', 'Mountains'), ('COUNTRYSIDE', 'Countryside'), ('GLACIERS', 'Glaciers'), ('WILDLIFE', 'Wildlife')], max_length=64, null=True)),
                ('interests', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FOOD', 'Food'), ('MUSIC', 'Music'), ('ART', 'Art'), ('TREKKING', 'Trekking'), ('ACTIVE', 'Active Activities'), ('RELAXING', 'Relaxing'), ('LANDSCAPES', 'Landscapes'), ('NATURE', 'Nature'), ('CULTURE', 'Culture')], max_length=64, null=True)),
                ('isActivated', models.BooleanField(default=True)),
                ('type_service', models.CharField(choices=[('AC', 'Accommodation'), ('NA', 'Non-accommodation')], max_length=64)),
                ('recommended', models.BooleanField(default=False)),
                ('real_supplier', models.CharField(max_length=64)),
                ('shown', models.BooleanField(default=True)),
                ('fcu', models.CharField(choices=[('Group', 'Group'), ('Person', 'Person')], max_length=64)),
                ('scu', models.PositiveSmallIntegerField()),
                ('lw_date', models.DateField(default=django.utils.timezone.now, verbose_name='last_working_date')),
                ('quality', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField()),
                ('clients', models.ManyToManyField(blank=True, related_name='available_clients', to='intranet.client')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='RateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_products', to='tariff.product')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TourplanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('supplier_code', models.CharField(blank=True, max_length=64, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=64, null=True)),
                ('service_code', models.CharField(blank=True, max_length=2, null=True)),
                ('location_code', models.CharField(blank=True, max_length=3, null=True)),
                ('option_code', models.CharField(blank=True, max_length=6, null=True)),
                ('option_description', models.CharField(blank=True, max_length=64, null=True)),
                ('option_comment', models.CharField(blank=True, max_length=64, null=True)),
                ('price_code', models.CharField(blank=True, max_length=2, null=True)),
                ('date_from', models.CharField(blank=True, max_length=64, null=True)),
                ('date_to', models.CharField(blank=True, max_length=64, null=True)),
                ('rate_status', models.CharField(blank=True, max_length=1, null=True)),
                ('serv_item', models.CharField(blank=True, max_length=64, null=True)),
                ('tax_list', models.CharField(blank=True, max_length=3, null=True)),
                ('fit_cost', models.CharField(blank=True, max_length=8, null=True)),
                ('fit_sell', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('pic1_url', models.CharField(blank=True, max_length=500, null=True)),
                ('pic2_url', models.CharField(blank=True, max_length=500, null=True)),
                ('pic3_url', models.CharField(blank=True, max_length=500, null=True)),
                ('children_ranking', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('disabled_ranking', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('sustentability_ranking', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('attractions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CITY', 'City'), ('FALLS', 'Falls'), ('MOUNTAINS', 'Mountains'), ('COUNTRYSIDE', 'Countryside'), ('GLACIERS', 'Glaciers'), ('WILDLIFE', 'Wildlife')], max_length=64, null=True)),
                ('interests', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FOOD', 'Food'), ('MUSIC', 'Music'), ('ART', 'Art'), ('TREKKING', 'Trekking'), ('ACTIVE', 'Active Activities'), ('RELAXING', 'Relaxing'), ('LANDSCAPES', 'Landscapes'), ('NATURE', 'Nature'), ('CULTURE', 'Culture')], max_length=64, null=True)),
                ('note', models.CharField(blank=True, default=None, max_length=500)),
                ('recommended', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('margin', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_products', to='tariff.suppliergroup')),
            ],
        ),
        migrations.CreateModel(
            name='RateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='from_date')),
                ('date_to', models.DateField(verbose_name='to_date')),
                ('season', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_rate', to='tariff.rategroup')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Provisional', 'Provisional')], max_length=64)),
                ('cost', models.FloatField()),
                ('margin', models.CharField(choices=[('Low', 'Low'), ('Regular', 'Regular'), ('High', 'High')], max_length=64)),
                ('increase', models.FloatField(blank=True, null=True)),
                ('sell', models.PositiveIntegerField()),
                ('sell_tourplan', models.PositiveIntegerField()),
                ('column_options', models.CharField(max_length=64)),
                ('has_rate', models.BooleanField(default=True)),
                ('text_value', models.CharField(blank=True, max_length=3, null=True)),
                ('rate_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_rates', to='tariff.rateline')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_products', to='tariff.location')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_products', to='tariff.productgroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='tariff.supplier'),
        ),
        migrations.CreateModel(
            name='FixedRateCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date_from', models.DateField(verbose_name='from_date')),
                ('date_to', models.DateField(verbose_name='to_date')),
                ('increase', models.FloatField(blank=True, null=True)),
                ('usd', models.BooleanField(default=True)),
                ('exchange', models.PositiveIntegerField(default=1)),
                ('value', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_rate_location', to='tariff.location')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('last_modification_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='last modification date')),
                ('closing_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='closing date')),
                ('type', models.CharField(choices=[('Calidad del servicio', 'Calidad del servicio'), ('Demora/rapidez', 'Demora/rapidez'), ('Salud/higiene', 'Salud/higiene'), ('Inclusiones', 'Otro'), ('Otro', 'Otro')], max_length=64)),
                ('content', models.CharField(max_length=3000)),
                ('complaint', models.BooleanField(default=False)),
                ('solution', models.CharField(blank=True, max_length=3000, null=True)),
                ('cost', models.FloatField(blank=True, default=0, null=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbac_destinations', to='tariff.location')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_suppliers', to='tariff.supplier')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_trips', to='intranet.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('usd', models.BooleanField(default=True)),
                ('exchange', models.PositiveIntegerField(default=1)),
                ('tax', models.CharField(choices=[(0, '0 - No taxes'), (10.5, '10.5 - Transport'), (21, '21 - Other')], max_length=64)),
                ('value', models.FloatField()),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='tariff.rate')),
            ],
        ),
    ]
