# Generated by Django 4.2.1 on 2025-05-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='children_ranking',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='disabled_ranking',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='children_ranking',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='disabled_ranking',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=64),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='children_ranking',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=64),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='disabled_ranking',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=64),
        ),
    ]
