# Generated by Django 4.2.1 on 2026-01-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='hotel_quality',
            field=models.CharField(blank=True, choices=[('3***', '3***'), ('3*** Superior', '3*** Superior'), ('4****', '4****'), ('4**** Superior', '4**** Superior'), ('5*****', '5*****'), ('5***** Lux', '5***** Lux'), ('Estancia', 'Estancia'), ('Boutique 4****', 'Boutique 4****'), ('Boutique 5*****', 'Boutique 5*****'), ('Boutique 5***** Lux', 'Boutique 5***** Lux'), ('Glamping', 'Glamping'), ('Winery', 'Winery')], max_length=64, null=True),
        ),
    ]
