# Generated by Django 4.2.1 on 2026-01-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_supplier_hotel_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='real_supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='description',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
