# Generated by Django 4.2.1 on 2025-05-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_alter_location_children_ranking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='margin',
            new_name='margin_acc',
        ),
        migrations.AddField(
            model_name='location',
            name='margin_svs',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
