# Generated by Django 4.2.1 on 2025-05-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0003_rename_margin_location_margin_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='sustentability_ranking',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sustentability_ranking',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='sustentability_ranking',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='pic1_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='pic2_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='pic3_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic1_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic2_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic3_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='pic1_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='pic2_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='pic3_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
