# Generated by Django 4.2.1 on 2026-01-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0003_remove_product_real_supplier_product_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='prepayment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
