# Generated by Django 4.2.1 on 2026-01-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0004_supplier_prepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliergroup',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_suppliers', to='tariff.location'),
            preserve_default=False,
        ),
    ]
