# Generated by Django 4.2.1 on 2025-05-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0004_location_sustentability_ranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedratecost',
            name='name',
            field=models.CharField(default='Entrance fee', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedratecost',
            name='value',
            field=models.PositiveBigIntegerField(default=20000),
            preserve_default=False,
        ),
    ]
