# Generated by Django 4.2.1 on 2026-01-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0005_suppliergroup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='type_service',
            field=models.CharField(choices=[('AC', 'Accommodation'), ('NA', 'Non-accommodation')], default='AC', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliergroup',
            name='type_service',
            field=models.CharField(choices=[('AC', 'Accommodation'), ('NA', 'Non-accommodation')], default='AC', max_length=64),
            preserve_default=False,
        ),
    ]
