# Generated by Django 4.2.1 on 2025-05-31 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0005_fixedratecost_name_fixedratecost_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='group',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='season',
        ),
        migrations.AlterField(
            model_name='costitem',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fixedratecost',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rate',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='RateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='from_date')),
                ('date_to', models.DateField(verbose_name='to_date')),
                ('season', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_rate', to='tariff.rategroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_products', to='tariff.product')),
            ],
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='line_rates', to='tariff.rateline'),
            preserve_default=False,
        ),
    ]
