# Generated by Django 4.2.1 on 2026-01-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0006_productgroup_type_service_suppliergroup_type_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='fixedratecost',
            name='rate',
            field=models.ManyToManyField(blank=True, related_name='rates_with_fixed', to='tariff.rate'),
        ),
    ]
