# Generated by Django 4.2.1 on 2026-01-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0007_alter_product_options_fixedratecost_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
