# Generated by Django 4.2.1 on 2025-06-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0007_rate_has_rates_rate_text_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='has_rates',
            new_name='has_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_products', to='tariff.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rategroup',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rate_products', to='tariff.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rateline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_line_products', to='tariff.product'),
        ),
    ]
