# Generated by Django 4.2.1 on 2025-06-01 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0008_rename_has_rates_rate_has_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateline',
            name='product',
        ),
    ]
