# Generated by Django 4.2.1 on 2026-01-29 20:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0008_alter_product_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date status')),
                ('type', models.CharField(choices=[('Update', 'Updated existing rates'), ('New', 'New property/product'), ('Add', 'Added rates to existing property/product')], max_length=64)),
                ('rate_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratelines', to='tariff.rateline')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
