# Generated by Django 4.2.1 on 2026-02-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0009_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rategroup',
            name='product',
        ),
        migrations.AddField(
            model_name='rategroup',
            name='product',
            field=models.ManyToManyField(related_name='rate_products', to='tariff.product'),
        ),
    ]
