# Generated by Django 4.2.1 on 2025-06-01 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0029_client_category_alter_user_usertype'),
        ('tariff', '0009_remove_rateline_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='available_clients', to='intranet.client'),
        ),
        migrations.AddField(
            model_name='rate',
            name='sell_tourplan',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rate',
            name='margin',
            field=models.CharField(choices=[('Low', 'Low'), ('Regular', 'Regular'), ('High', 'High')], max_length=64),
        ),
        migrations.CreateModel(
            name='CsvFileTourplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvFiles')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
