# Generated by Django 4.2.1 on 2025-06-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0010_product_clients_rate_sell_tourplan_alter_rate_margin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfiletourplan',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='csvfiletourplan',
            name='user',
        ),
        migrations.AddField(
            model_name='csvfiletourplan',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
