# Generated by Django 4.2.1 on 2026-02-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0010_remove_rategroup_product_rategroup_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rategroup',
            name='product',
        ),
        migrations.AddField(
            model_name='rategroup',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rate_products', to='tariff.product'),
            preserve_default=False,
        ),
    ]
