# Generated by Django 4.2.1 on 2026-02-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0011_remove_rategroup_product_rategroup_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='childNote',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='child_note',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='closing_note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='stay_note',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
