# Generated by Django 4.2.1 on 2025-06-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0011_remove_csvfiletourplan_activated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourplanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('supplier_code', models.CharField(blank=True, max_length=64, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=64, null=True)),
                ('service_code', models.CharField(blank=True, max_length=2, null=True)),
                ('location_code', models.CharField(blank=True, max_length=3, null=True)),
                ('option_code', models.CharField(blank=True, max_length=6, null=True)),
                ('option_description', models.CharField(blank=True, max_length=64, null=True)),
                ('option_comment', models.CharField(blank=True, max_length=64, null=True)),
                ('price_code', models.CharField(blank=True, max_length=2, null=True)),
                ('date_from', models.CharField(blank=True, max_length=64, null=True)),
                ('date_to', models.CharField(blank=True, max_length=64, null=True)),
                ('rate_status', models.CharField(blank=True, max_length=1, null=True)),
                ('serv_item', models.CharField(blank=True, max_length=64, null=True)),
                ('tax_list', models.CharField(blank=True, max_length=3, null=True)),
                ('fit_cost', models.IntegerField(blank=True, null=True)),
                ('fit_sell', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
