# Generated by Django 4.2.1 on 2025-06-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0012_tourplanline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourplanline',
            name='fit_cost',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tourplanline',
            name='fit_sell',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
