# Generated by Django 4.2.1 on 2026-02-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0012_product_childnote_supplier_child_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='childNote',
            new_name='child_note',
        ),
    ]
