# Generated by Django 4.2.1 on 2026-02-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0013_rename_childnote_product_child_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tour_timing',
            field=models.CharField(choices=[('AM', 'Morning'), ('PM', 'Afternoon'), ('Night', 'Evening')], default='AM', max_length=64),
            preserve_default=False,
        ),
    ]
