# Generated by Django 4.2 on 2025-09-16 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0049_entry_exception_entry_timingstatus'),
        ('tariff', '0013_alter_tourplanline_fit_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('last_modification_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='last modification date')),
                ('closing_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='closing date')),
                ('type', models.CharField(choices=[('Calidad del servicio', 'Calidad del servicio'), ('Demora/rapidez', 'Demora/rapidez'), ('Salud/higiene', 'Salud/higiene'), ('Inclusiones', 'Otro'), ('Otro', 'Otro')], max_length=64)),
                ('content', models.CharField(max_length=1024)),
                ('cost', models.FloatField()),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbac_destinations', to='tariff.location')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_suppliers', to='tariff.supplier')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_trips', to='intranet.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
