# Generated by Django 4.2.1 on 2026-02-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0014_product_tour_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tour_timing',
            field=models.CharField(blank=True, choices=[('AM', 'Morning'), ('PM', 'Afternoon'), ('Night', 'Evening')], max_length=64, null=True),
        ),
    ]
