# Generated by Django 4.2 on 2025-09-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0014_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='complaint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='solution',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
