# Generated by Django 4.2.1 on 2026-02-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0015_alter_product_tour_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='tour_timing',
            field=models.CharField(blank=True, choices=[('AM', 'Morning'), ('PM', 'Afternoon'), ('AM/PM', 'Morning & Afternoon'), ('Night', 'Evening')], max_length=64, null=True),
        ),
    ]
