# Generated by Django 4.2.1 on 2026-03-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0016_change_amount_alter_product_tour_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
