# Generated by Django 4.2.1 on 2026-03-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0017_location_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='update_tp',
            field=models.BooleanField(default=True),
        ),
    ]
