# Generated by Django 4.2.1 on 2026-03-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0018_supplier_update_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='margin_info',
            field=models.CharField(choices=[('Low', 'Low'), ('Regular', 'Regular'), ('High', 'High')], default='Regular', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='hotel_quality',
            field=models.CharField(blank=True, choices=[('3***', '3***'), ('3*** Superior', '3*** Superior'), ('4****', '4****'), ('4**** Superior', '4**** Superior'), ('5*****', '5*****'), ('5***** Lux', '5***** Lux'), ('Estancia', 'Estancia'), ('Boutique 4****', 'Boutique 4****'), ('Boutique 5*****', 'Boutique 5*****'), ('Boutique Luxury', 'Boutique Luxury'), ('Glamping', 'Glamping'), ('Winery Standard', 'Winery Standard'), ('Winery Superior', 'Winery Superior'), ('Winery Luxury', 'Winery Luxury')], max_length=64, null=True),
        ),
    ]
