# Generated by Django 4.2.1 on 2026-03-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0019_supplier_margin_info_alter_supplier_hotel_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='costitem',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
