# Generated by Django 4.2.1 on 2026-03-26 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0011_add_margin_reviewed'),
        ('tariff', '0025_rate_has_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='destination',
        ),
        migrations.AddField(
            model_name='feedback',
            name='brief_summary',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Resumen breve'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='email_sender',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(choices=[('positivo', 'Positivo'), ('neutral', 'Neutral'), ('negativo', 'Negativo')], default='neutral', max_length=16),
        ),
        migrations.AddField(
            model_name='feedback',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('email', 'Email')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_seguimiento', 'En seguimiento'), ('cerrado', 'Cerrado')], default='abierto', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='supplier_raw',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Proveedor (texto libre)'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_trips', to='intranet.trip'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('Calidad del servicio', 'Calidad del servicio'), ('Demora/rapidez', 'Demora/rapidez'), ('Salud/higiene', 'Salud/higiene'), ('Inclusiones', 'Inclusiones'), ('Otro', 'Otro')], max_length=64),
        ),
        migrations.CreateModel(
            name='FeedbackInboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField()),
                ('email_subject', models.CharField(blank=True, default='', max_length=500)),
                ('email_body', models.TextField()),
                ('email_sender', models.EmailField(max_length=254)),
                ('gmail_label', models.CharField(blank=True, default='', max_length=100)),
                ('gmail_message_id', models.CharField(max_length=200, unique=True)),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('descartado', 'Descartado')], default='pendiente', max_length=20)),
                ('resolved_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_source', to='tariff.feedback')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
