# Generated by Django 4.2.1 on 2026-03-26 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tariff', '0026_feedback_update_and_inbox_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name': 'Entidad de feedback',
                'verbose_name_plural': 'Entidades de feedback',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='supplier_raw',
        ),
        migrations.AddField(
            model_name='feedback',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='verbatim',
            field=models.TextField(blank=True, default='', verbose_name='Texto original del pasajero'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='target_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entities', to='tariff.feedbackentity'),
        ),
    ]
