# Generated by Django 4.2.1 on 2026-03-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0029_supplier_provisional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourplanline',
            name='is_revised',
            field=models.BooleanField(default=True),
        ),
    ]
