# Generated by Django 4.2.1 on 2026-03-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0030_tourplanline_is_revised'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourplanline',
            name='is_revised',
        ),
        migrations.AddField(
            model_name='rateline',
            name='is_revised',
            field=models.BooleanField(default=True),
        ),
    ]
