# Generated by Django 4.2.1 on 2026-03-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0031_remove_tourplanline_is_revised_rateline_is_revised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='brief_summary',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Resumen breve'),
        ),
    ]
