# Generated by Django 4.2.1 on 2026-04-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0032_brief_summary_max120'),
    ]

    operations = [
        migrations.AddField(
            model_name='costitem',
            name='increase',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
