# Generated by Django 4.2.1 on 2026-06-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0036_product_tp_location_code'),
        ('tariff', '0036_supplier_tp_location_code'),
    ]

    operations = [
    ]
