# Generated by Django 4.2.1 on 2026-06-16 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tariff', '0038_supplier_highlights_notes_sustainable_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='tp_location_code',
        ),
        migrations.AddField(
            model_name='feedback',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del feedback'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='hotel_quality',
            field=models.CharField(blank=True, choices=[('5***** Luxury', '5***** Luxury'), ('5***** Superior', '5***** Superior'), ('5***** Standard', '5***** Standard'), ('4**** Superior', '4**** Superior'), ('4**** Standard', '4**** Standard'), ('3*** Superior', '3*** Superior'), ('3*** Standard', '3*** Standard'), ('Boutique Luxury', 'Boutique Luxury'), ('Boutique Superior', 'Boutique Superior'), ('Boutique Standard', 'Boutique Standard'), ('Winery Luxury', 'Winery Luxury'), ('Winery Superior', 'Winery Superior'), ('Winery Standard', 'Winery Standard'), ('Estancia Luxury', 'Estancia Luxury'), ('Estancia Superior', 'Estancia Superior'), ('Estancia Standard', 'Estancia Standard'), ('Glamping Superior', 'Glamping Superior'), ('Glamping Standard', 'Glamping Standard')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sustainableaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
