# Generated by Django 4.2.1 on 2026-06-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0039_feedback_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='priority',
            field=models.CharField(blank=True, choices=[('1 - BAJA - min', 'BAJA - min'), ('2 - BAJA - standard', 'BAJA - standard'), ('3 - BAJA - plus', 'BAJA - plus'), ('4 - MED - min', 'MED - min'), ('5 - MED - standard', 'MED - standard'), ('6 - MED - pide urgente', 'MED - pide urgente'), ('7 - ALTA - standard', 'ALTA - standard'), ('8 - ALTA - pide urgente', 'ALTA - pide urgente'), ('9 - ALTA - cliente nuevo', 'ALTA - cliente nuevo'), ('10 - ALTA - last minute', 'ALTA - last minute')], default='', max_length=64, verbose_name='Prioridad'),
        ),
    ]
