# Generated by Django 4.2.1 on 2026-06-16 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0023_driver_model'),
        ('tariff', '0040_feedback_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='target_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_drivers', to='intranet.driver'),
        ),
    ]
