# Generated by Django 4.2.1 on 2026-07-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0041_driver_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Categoría Hertz (ej: H1, K1, N1)')),
                ('name', models.CharField(max_length=150, verbose_name='Modelo (ej: Fiat Cronos Mt 4 Ptas)')),
                ('order', models.PositiveIntegerField(default=9999)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('pic1_url', models.CharField(blank=True, max_length=500, null=True)),
                ('isActivated', models.BooleanField(default=True)),
                ('airport_pct', models.FloatField(blank=True, null=True, verbose_name='Airport % (vacío = usar default general)')),
                ('smart_pct', models.FloatField(blank=True, null=True, verbose_name='Smart % (vacío = usar default general)')),
                ('cover_pct', models.FloatField(blank=True, null=True, verbose_name='Cover % (vacío = usar default general)')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_categories', to='tariff.location')),
            ],
            options={
                'verbose_name_plural': 'Car categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CarHireConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.FloatField(default=0.82, verbose_name='Markup general')),
                ('exchange', models.PositiveIntegerField(default=1400, verbose_name='Tipo de cambio (ARS x USD)')),
                ('increase', models.FloatField(default=0, verbose_name='Aumento general %')),
                ('default_airport_pct', models.FloatField(default=23, verbose_name='Airport % (default, sobre venta RACK)')),
                ('default_smart_pct', models.FloatField(default=38, verbose_name='Smart % (default, sobre venta RACK)')),
                ('default_cover_pct', models.FloatField(default=15, verbose_name='Cover % (default, sobre venta RACK)')),
            ],
        ),
        migrations.CreateModel(
            name='CarRateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tarifa estándar', max_length=64)),
                ('order', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_groups', to='tariff.carcategory')),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20),
        ),
        migrations.CreateModel(
            name='CarRateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='from_date')),
                ('date_to', models.DateField(verbose_name='to_date')),
                ('season', models.CharField(blank=True, default='', max_length=64)),
                ('is_revised', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_rate', to='tariff.carrategroup')),
            ],
        ),
        migrations.CreateModel(
            name='CarRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Provisional', 'Provisional')], default='Confirmed', max_length=64)),
                ('increase', models.FloatField(blank=True, default=0, null=True)),
                ('cost', models.FloatField(default=0, verbose_name='Costo x día (ARS)')),
                ('sell', models.PositiveIntegerField(default=0, verbose_name='Venta x día (USD)')),
                ('locked', models.BooleanField(default=False)),
                ('rate_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_rates', to='tariff.carrateline')),
            ],
        ),
        migrations.CreateModel(
            name='CarFixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('usd', models.BooleanField(default=True)),
                ('exchange', models.PositiveIntegerField(default=1)),
                ('value', models.FloatField(default=0, verbose_name='Costo')),
                ('fcu', models.CharField(choices=[('Group', 'Group'), ('Person', 'Person')], default='Group', max_length=64)),
                ('increase', models.FloatField(blank=True, default=0, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_fixed_costs', to='tariff.location', verbose_name='Destino (vacío = todos)')),
            ],
        ),
        migrations.CreateModel(
            name='CarExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AIRPORT', 'Airport'), ('SMART', 'Smart'), ('COVER', 'Cover')], max_length=20)),
                ('cost', models.FloatField(default=0, verbose_name='Costo x día (ARS)')),
                ('sell', models.PositiveIntegerField(default=0, verbose_name='Venta x día (USD)')),
                ('manual_override', models.BooleanField(default=False, verbose_name='Cargado a mano (no recalcular automático)')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='tariff.carrate')),
            ],
            options={
                'unique_together': {('rate', 'type')},
            },
        ),
    ]
