# Generated by Django 4.2.1 on 2026-08-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0051_supplier_note_aliwen_note_audley'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcategory',
            name='transmission',
            field=models.CharField(blank=True, choices=[('M', 'Manual'), ('A', 'Automatic')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='carextra',
            name='type',
            field=models.CharField(choices=[('AIRPORT', 'Airport'), ('SMART', 'Smart'), ('COVER', 'Tyres Cover')], max_length=20),
        ),
    ]
