# Generated by Django 4.2.1 on 2026-09-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0052_alter_carcategory_transmission_alter_carextra_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='isActivated',
            field=models.BooleanField(default=True, verbose_name='Activo en el tarifario'),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
